// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCleYnVo1bRX2cNS0eFlGfreW8-EA8dedA',
    appId: '1:19681294972:web:556496ce5004a00375e7f9',
    messagingSenderId: '19681294972',
    projectId: 'familyhealthmanager',
    authDomain: 'familyhealthmanager.firebaseapp.com',
    storageBucket: 'familyhealthmanager.appspot.com',
    measurementId: 'G-89R9EQSDL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXUXctUP1c8CNIQ6HEoUgnfmNNIDH7b34',
    appId: '1:19681294972:android:a06bb4768efe8fb975e7f9',
    messagingSenderId: '19681294972',
    projectId: 'familyhealthmanager',
    storageBucket: 'familyhealthmanager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwjnUWlskpWIuzmpilQc7IEeljCZJ7z4M',
    appId: '1:19681294972:ios:247805272999ac3975e7f9',
    messagingSenderId: '19681294972',
    projectId: 'familyhealthmanager',
    storageBucket: 'familyhealthmanager.appspot.com',
    iosClientId: '19681294972-lc5gpcodlnmlu6jdhe07m0di4uhs4pu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.familyHealthManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwjnUWlskpWIuzmpilQc7IEeljCZJ7z4M',
    appId: '1:19681294972:ios:247805272999ac3975e7f9',
    messagingSenderId: '19681294972',
    projectId: 'familyhealthmanager',
    storageBucket: 'familyhealthmanager.appspot.com',
    iosClientId: '19681294972-lc5gpcodlnmlu6jdhe07m0di4uhs4pu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.familyHealthManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCleYnVo1bRX2cNS0eFlGfreW8-EA8dedA',
    appId: '1:19681294972:web:8f0efc8da801e38875e7f9',
    messagingSenderId: '19681294972',
    projectId: 'familyhealthmanager',
    authDomain: 'familyhealthmanager.firebaseapp.com',
    storageBucket: 'familyhealthmanager.appspot.com',
    measurementId: 'G-3C67MW26W4',
  );
}
